Experiment 1: Installing TensorFlow

In [5]:
pip install tensorflow

In [6]:
import tensorflow as tf

print(tf.__version__)
print(tf.config.list_physical_devices('GPU'))


2.19.0
[]


Experiment 2: Creating and Displaying Tensors

In [9]:
a = tf.constant(5)
print(a)

v = tf.constant([10, 20, 30])
print(v)

m = tf.constant([
    [1, 2],
    [3, 4]
])

print(m)

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([10 20 30], shape=(3,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


Experiment 3: Arithmetic Operations on Tensor

In [11]:
a = tf.constant([10, 20])
b = tf.constant([5, 15])

s = tf.add(a, b)
print(s)

d = tf.subtract(a, b)
print(d)

p = tf.multiply(a, b)
print(p)

d = tf.divide(a, b)
print(d)

tf.Tensor([15 35], shape=(2,), dtype=int32)
tf.Tensor([5 5], shape=(2,), dtype=int32)
tf.Tensor([ 50 300], shape=(2,), dtype=int32)
tf.Tensor([2.         1.33333333], shape=(2,), dtype=float64)


Experiment 4: Displaying info of a Tensor

In [12]:
tensor = tf.constant(50)

print("Data type:", tensor.dtype)

print("Shape:", tensor.shape)

print("Number of dimensions:", tensor.ndim)

Data type: <dtype: 'int32'>
Shape: ()
Number of dimensions: 0


Experiment 5: converting a numpy array to tensor

In [13]:
import numpy as np

np_array = np.array([[1, 2, 3],
                     [4, 5, 6]])

tensor = tf.convert_to_tensor(np_array)

print("Tensor:")
print(tensor)

Tensor:
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int64)
